//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryLoadBookings
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eInvoiceEntities : DbContext
    {
        public eInvoiceEntities()
            : base("name=eInvoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_BOHP> Tbl_BOHP { get; set; }
        public virtual DbSet<Tbl_BOCP> Tbl_BOCP { get; set; }
        public virtual DbSet<Tbl_BODP> Tbl_BODP { get; set; }
        public virtual DbSet<Tbl_BOIP> Tbl_BOIP { get; set; }
    
        public virtual int Truncate_Booking_Order_Tables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Truncate_Booking_Order_Tables");
        }
    }
}
