//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryLoadBookings
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaundryCustomer
    {
        public int Id { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string Status { get; set; }
        public Nullable<int> Load { get; set; }
        public Nullable<bool> BiWeekly { get; set; }
        public Nullable<bool> ThisWeek { get; set; }
    }
}
