//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryLoadBookings
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SummerPromoEntities : DbContext
    {
        public SummerPromoEntities()
            : base("name=SummerPromoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Laundry> Laundries { get; set; }
        public virtual DbSet<LaundryItem> LaundryItems { get; set; }
        public virtual DbSet<LaundryCustomer> LaundryCustomers { get; set; }
    }
}
