//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryLoadBookings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BOCP
    {
        public decimal CO407F { get; set; }
        public string CO99A { get; set; }
        public string CO300G { get; set; }
        public string CO100A { get; set; }
        public System.DateTime CO408N { get; set; }
        public decimal CO403N { get; set; }
        public string CO408Y { get; set; }
        public string CO408I { get; set; }
        public string CO1UA { get; set; }
        public decimal CO1ZA { get; set; }
        public string CO1TA { get; set; }
        public string CO408H { get; set; }
        public decimal CO416P { get; set; }
        public decimal CO408Z { get; set; }
        public string CO408L { get; set; }
        public System.DateTime CO408X { get; set; }
        public decimal CO402Q { get; set; }
        public decimal CO408P { get; set; }
        public System.DateTime CO408O { get; set; }
        public decimal CO408M { get; set; }
        public string CO403R { get; set; }
        public string CO2A { get; set; }
        public decimal CO408W { get; set; }
        public decimal CO409V { get; set; }
        public string VEN001H { get; set; }
        public string CO2IA { get; set; }
        public decimal CO401E { get; set; }
        public decimal CO401F { get; set; }
        public decimal IM101M { get; set; }
        public string CO408F { get; set; }
        public System.DateTime BK0001 { get; set; }
        public System.DateTime CO408G { get; set; }
        public decimal CO408C { get; set; }
        public System.DateTime OBF002 { get; set; }
        public System.DateTime OBF003 { get; set; }
        public System.DateTime OBF005 { get; set; }
        public System.DateTime OBF006 { get; set; }
        public string MBFUID { get; set; }
        public string MBFFID { get; set; }
        public string MBFRCS { get; set; }
    }
}
