//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryLoadBookings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BOHP
    {
        public decimal CO407F { get; set; }
        public string CO408D { get; set; }
        public string CO408E { get; set; }
        public string CO408I { get; set; }
        public string CO408H { get; set; }
        public string CO408T { get; set; }
        public string CO9992 { get; set; }
        public string CO408U { get; set; }
        public Nullable<decimal> CO408V { get; set; }
        public string CO2A { get; set; }
        public Nullable<decimal> CO408W { get; set; }
        public Nullable<decimal> CO409V { get; set; }
        public string CO408F { get; set; }
        public Nullable<System.DateTime> CO408G { get; set; }
        public Nullable<System.DateTime> OBF002 { get; set; }
        public Nullable<System.DateTime> OBF003 { get; set; }
        public Nullable<System.DateTime> OBF005 { get; set; }
        public Nullable<System.DateTime> OBF006 { get; set; }
        public string MBFUID { get; set; }
        public string MBFFID { get; set; }
        public string MBFRCS { get; set; }
    }
}
