//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryLoadBookings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BOIP
    {
        public decimal CO407F { get; set; }
        public string CO1UA { get; set; }
        public decimal CO1ZA { get; set; }
        public string CO1TA { get; set; }
        public decimal CO408Z { get; set; }
        public string CO408L { get; set; }
        public System.DateTime CO408X { get; set; }
        public decimal CO408M { get; set; }
        public decimal CO408C { get; set; }
        public string VEN001H { get; set; }
        public decimal CO401E { get; set; }
        public decimal CO401F { get; set; }
        public System.DateTime OBF002 { get; set; }
        public System.DateTime OBF003 { get; set; }
        public System.DateTime OBF005 { get; set; }
        public System.DateTime OBF006 { get; set; }
        public string MBFUID { get; set; }
        public string MBFFID { get; set; }
        public string MBFRCS { get; set; }
    }
}
