//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryLoadBookings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BODP
    {
        public decimal CO407F { get; set; }
        public System.DateTime CO408N { get; set; }
        public System.DateTime CO409U { get; set; }
        public System.DateTime OBF002 { get; set; }
        public System.DateTime OBF003 { get; set; }
        public System.DateTime OBF005 { get; set; }
        public System.DateTime OBF006 { get; set; }
        public string MBFUID { get; set; }
        public string MBFFID { get; set; }
        public string MBFRCS { get; set; }
    }
}
